name = input("what is your name?: ")
print("your name is : ", name)
age=int(input("what is your age?: "))
print("your age is: ", age)
heigh=float(input("type your heigh with using float numbers only: "))
print("your heigh is: ", heigh)
